import crypto from 'crypto';
import { getGeminiModel, generateContentWithRetry } from '@/lib/gemini';
import { SYSTEM_BASE, buildAnalyzePrompt, buildRepairPrompt } from '@/lib/prompts';
import {
  AnalyzeApiRequest,
  AnalyzeApiRequestSchema,
  AnalyzeApiRequestParsed,
  AnalyzeResultSchema,
  AnalyzeResult,
  ClauseCard,
} from '@/lib/schemas';
import { verifyQuotes } from '@/lib/verify';

// In-memory LRU-like cache for document analysis results
const cache = new Map<string, { timestamp: number; result: AnalyzeResult }>();
const CACHE_TTL_MS = 1000 * 60 * 30; // 30 minutes
const MAX_CACHE_SIZE = 100;

function computeCacheKey(params: AnalyzeApiRequestParsed): string {
  const hash = crypto.createHash('sha256');
  hash.update(params.documentText);
  hash.update(params.documentType);
  hash.update(params.jurisdictionState);
  hash.update(params.language);
  hash.update(String(Boolean(params.isScanned)));
  return hash.digest('hex');
}

/**
 * Normalizes raw model output to handle common JSON key aliases and variations.
 * Bridges differences between prompt key interpretations and strict Zod validation.
 */
function normalizeModelOutput(raw: Record<string, unknown>): Record<string, unknown> {
  const normalized: Record<string, unknown> = { ...raw };

  // 1. isLegalDocument
  if (typeof normalized.isLegalDocument !== 'boolean') {
    normalized.isLegalDocument = true;
  }

  // 2. plainSummary (might be plainLanguageSummary or plain_summary)
  if (!normalized.plainSummary && normalized.plainLanguageSummary) {
    normalized.plainSummary = normalized.plainLanguageSummary;
  }
  if (!normalized.plainSummary && normalized.plain_summary) {
    normalized.plainSummary = normalized.plain_summary;
  }
  if (!normalized.plainSummary || typeof normalized.plainSummary !== 'object') {
    normalized.plainSummary = {
      whatAmIAgreeingTo: 'Summary not generated by model.',
      parties: {
        userRole: 'First Party / User',
        userName: 'Not explicitly named',
        counterpartyRole: 'Counterparty',
        counterpartyName: 'Not explicitly named',
      },
      termDuration: 'Not explicitly specified',
      moneyObligations: 'Not explicitly specified',
      terminationConditions: 'Not explicitly specified',
    };
  }

  // 3. clauses (might be significantClauseCards or significant_clauses)
  if (!normalized.clauses && normalized.significantClauseCards) {
    normalized.clauses = normalized.significantClauseCards;
  }
  if (!normalized.clauses && normalized.significant_clauses) {
    normalized.clauses = normalized.significant_clauses;
  }
  if (!Array.isArray(normalized.clauses)) {
    normalized.clauses = [];
  } else {
    normalized.clauses = (normalized.clauses as Record<string, unknown>[]).map((c, idx) => ({
      id: c.id ? String(c.id) : `clause-${idx + 1}`,
      title: c.title || 'Untitled Clause',
      verbatimQuote: c.verbatimQuote || c.quote || '',
      pageNumber: typeof c.pageNumber === 'number' ? c.pageNumber : 1,
      plainExplanation: c.plainExplanation || c.explanation || '',
      risk: ['low', 'medium', 'high'].includes(String(c.risk).toLowerCase())
        ? String(c.risk).toLowerCase()
        : 'medium',
      whyItMatters: c.whyItMatters || c.practicalImpact || 'Important to review.',
      category: [
        'payment',
        'termination',
        'renewal',
        'liability',
        'penalties',
        'privacy',
        'dispute-resolution',
        'other',
      ].includes(String(c.category).toLowerCase())
        ? String(c.category).toLowerCase()
        : 'other',
      isVerified: true,
      matchConfidence: 100,
    }));
  }

  // 4. formalitiesCheck (might be formalities_check)
  if (!normalized.formalitiesCheck && normalized.formalities_check) {
    normalized.formalitiesCheck = normalized.formalities_check;
  }
  const defaultFormalities = {
    stampDutyOrEStamp: {
      status: 'unclear',
      details: 'Not explicitly referenced',
      practicalAdvice: 'Check stamp duty rules with a local registrar or lawyer.',
    },
    registration: {
      status: 'unclear',
      details: 'Registration status not explicitly stated',
      practicalAdvice: 'Agreements exceeding 11 months require mandatory registration in India.',
    },
    witnesses: {
      status: 'unclear',
      details: 'Witness execution details not detected',
      practicalAdvice: 'Ensure two independent witnesses sign execution copies.',
    },
    notarization: {
      status: 'unclear',
      details: 'Notary seal not detected',
      practicalAdvice: 'Confirm if notarization or attestation is desired.',
    },
    signaturesOfAllParties: {
      status: 'unclear',
      details: 'Execution block present',
      practicalAdvice: 'Verify all parties execute every page of the physical copy.',
    },
    panAadhaarReferences: {
      status: 'unclear',
      details: 'Government identity details not explicitly recorded',
      practicalAdvice: 'Keep self-attested copies of government ID on record.',
    },
    datedExecution: {
      status: 'unclear',
      details: 'Execution date present',
      practicalAdvice: 'Verify execution date aligns with stamp duty issuance.',
    },
  };

  if (!normalized.formalitiesCheck || typeof normalized.formalitiesCheck !== 'object') {
    normalized.formalitiesCheck = defaultFormalities;
  } else {
    const fc = normalized.formalitiesCheck as Record<string, Record<string, unknown>>;
    const requiredKeys = [
      'stampDutyOrEStamp',
      'registration',
      'witnesses',
      'notarization',
      'signaturesOfAllParties',
      'panAadhaarReferences',
      'datedExecution',
    ] as const;

    for (const key of requiredKeys) {
      if (!fc[key] || typeof fc[key] !== 'object') {
        fc[key] = defaultFormalities[key];
      } else {
        const item = fc[key];
        const status = String(item.status || 'unclear').toLowerCase();
        item.status = ['found', 'not_found', 'unclear'].includes(status) ? status : 'unclear';
        item.details = item.details ? String(item.details) : 'Not explicitly detailed';
        item.practicalAdvice = item.practicalAdvice
          ? String(item.practicalAdvice)
          : defaultFormalities[key].practicalAdvice;
      }
    }
  }

  // 5. inconsistencies (might be inconsistencyAndContradictionDetection)
  if (!normalized.inconsistencies && normalized.inconsistencyAndContradictionDetection) {
    normalized.inconsistencies = normalized.inconsistencyAndContradictionDetection;
  }
  if (!Array.isArray(normalized.inconsistencies)) {
    normalized.inconsistencies = [];
  }

  // 6. missingProtections (might be array of strings or missing_protections)
  if (!normalized.missingProtections && normalized.missing_protections) {
    normalized.missingProtections = normalized.missing_protections;
  }
  if (Array.isArray(normalized.missingProtections)) {
    normalized.missingProtections = (
      normalized.missingProtections as (string | Record<string, unknown>)[]
    ).map((item, idx) => {
      if (typeof item === 'string') {
        return {
          id: `mp-${idx + 1}`,
          topic: item,
          whyExpected: 'Commonly included in standard agreements for protection.',
          practicalRisk:
            'Absence may leave you exposed in case of dispute or premature termination.',
          recommendation: `Request the counterparty to insert a clear clause covering ${item}.`,
        };
      }
      return {
        id: item.id ? String(item.id) : `mp-${idx + 1}`,
        topic: item.topic || 'Standard Protection',
        whyExpected: item.whyExpected || 'Expected standard provision in Indian agreements.',
        practicalRisk: item.practicalRisk || 'Lack of clarity may lead to disputes.',
        recommendation:
          item.recommendation || 'Consult counterparty or counsel to add this clause.',
      };
    });
  } else {
    normalized.missingProtections = [];
  }

  // 7. keyDatesAndDeadlines (might be an object with phases, or array)
  if (!normalized.keyDatesAndDeadlines && normalized.keyDates) {
    normalized.keyDatesAndDeadlines = normalized.keyDates;
  }
  if (!normalized.keyDatesAndDeadlines && normalized.key_dates_and_deadlines) {
    normalized.keyDatesAndDeadlines = normalized.key_dates_and_deadlines;
  }
  if (
    normalized.keyDatesAndDeadlines &&
    !Array.isArray(normalized.keyDatesAndDeadlines) &&
    typeof normalized.keyDatesAndDeadlines === 'object'
  ) {
    // If returned as { deadlines: [...] } or grouped by phase
    const obj = normalized.keyDatesAndDeadlines as Record<string, unknown>;
    const flattened: Record<string, unknown>[] = [];
    for (const [k, v] of Object.entries(obj)) {
      if (Array.isArray(v)) {
        flattened.push(
          ...(v as Record<string, unknown>[]).map((item) =>
            typeof item === 'string' ? { event: `${k}: ${item}` } : { ...item, phase: k }
          )
        );
      } else if (typeof v === 'string') {
        flattened.push({ event: k, dateOrTimeline: v });
      }
    }
    normalized.keyDatesAndDeadlines = flattened;
  }
  if (Array.isArray(normalized.keyDatesAndDeadlines)) {
    normalized.keyDatesAndDeadlines = (
      normalized.keyDatesAndDeadlines as Record<string, unknown>[]
    ).map((kd, idx) => ({
      id: kd.id ? String(kd.id) : `kd-${idx + 1}`,
      event: kd.event || kd.title || 'Important Deadline / Event',
      dateOrPeriod: kd.dateOrPeriod || kd.dateOrTimeline || '',
      dateOrTimeline: kd.dateOrTimeline || kd.dateOrPeriod || '',
      actionRequired: kd.actionRequired || '',
      consequenceIfMissed: kd.consequenceIfMissed || '',
      pageNumber: typeof kd.pageNumber === 'number' ? kd.pageNumber : 1,
    }));
  } else {
    normalized.keyDatesAndDeadlines = [];
  }

  // 8. actionChecklist (might be an object with before_signing, during_term, at_termination)
  if (!normalized.actionChecklist && normalized.action_checklist) {
    normalized.actionChecklist = normalized.action_checklist;
  }
  if (
    normalized.actionChecklist &&
    !Array.isArray(normalized.actionChecklist) &&
    typeof normalized.actionChecklist === 'object'
  ) {
    const obj = normalized.actionChecklist as Record<string, unknown>;
    const flattened: Record<string, unknown>[] = [];
    const validPhases = ['before_signing', 'during_term', 'at_termination'] as const;

    for (const phase of validPhases) {
      const items = obj[phase];
      if (Array.isArray(items)) {
        for (const item of items) {
          if (typeof item === 'string') {
            flattened.push({
              phase,
              item,
              details: '',
              criticality: 'recommended',
            });
          } else if (typeof item === 'object' && item !== null) {
            flattened.push({
              phase,
              item:
                (item as Record<string, unknown>).item ||
                (item as Record<string, unknown>).task ||
                'Action item',
              details: (item as Record<string, unknown>).details || '',
              criticality: ['must_do', 'recommended', 'optional'].includes(
                String((item as Record<string, unknown>).criticality)
              )
                ? (item as Record<string, unknown>).criticality
                : 'recommended',
            });
          }
        }
      }
    }
    // Also check for camelCase phases like beforeSigning, duringTerm, atTermination
    const camelMap: Record<string, 'before_signing' | 'during_term' | 'at_termination'> = {
      beforeSigning: 'before_signing',
      duringTerm: 'during_term',
      atTermination: 'at_termination',
    };
    for (const [camelKey, standardPhase] of Object.entries(camelMap)) {
      const items = obj[camelKey];
      if (Array.isArray(items)) {
        for (const item of items) {
          if (typeof item === 'string') {
            flattened.push({
              phase: standardPhase,
              item,
              details: '',
              criticality: 'recommended',
            });
          } else if (typeof item === 'object' && item !== null) {
            flattened.push({
              phase: standardPhase,
              item:
                (item as Record<string, unknown>).item ||
                (item as Record<string, unknown>).task ||
                'Action item',
              details: (item as Record<string, unknown>).details || '',
              criticality: ['must_do', 'recommended', 'optional'].includes(
                String((item as Record<string, unknown>).criticality)
              )
                ? (item as Record<string, unknown>).criticality
                : 'recommended',
            });
          }
        }
      }
    }
    normalized.actionChecklist = flattened;
  }
  if (Array.isArray(normalized.actionChecklist)) {
    normalized.actionChecklist = (normalized.actionChecklist as Record<string, unknown>[]).map(
      (ac, idx) => ({
        id: ac.id ? String(ac.id) : `ac-${idx + 1}`,
        phase: ['before_signing', 'during_term', 'at_termination'].includes(String(ac.phase))
          ? String(ac.phase)
          : 'before_signing',
        item: ac.item || ac.task || 'Action item',
        task: ac.task || ac.item || '',
        details: ac.details ? String(ac.details) : '',
        criticality: ['must_do', 'recommended', 'optional'].includes(String(ac.criticality))
          ? String(ac.criticality)
          : 'recommended',
      })
    );
  } else {
    normalized.actionChecklist = [];
  }

  // 9. questionsToAsk (might be questions_to_ask)
  if (!normalized.questionsToAsk && normalized.questions_to_ask) {
    normalized.questionsToAsk = normalized.questions_to_ask;
  }
  if (Array.isArray(normalized.questionsToAsk)) {
    normalized.questionsToAsk = (
      normalized.questionsToAsk as (string | Record<string, unknown>)[]
    ).map((q, idx) => {
      if (typeof q === 'string') {
        return {
          id: `q-${idx + 1}`,
          priority: 'medium',
          question: q,
          askTo: 'both',
          contextAndTalkingPoint: 'Discuss and seek clarification before execution.',
        };
      }
      return {
        id: q.id ? String(q.id) : `q-${idx + 1}`,
        priority: ['high', 'medium', 'low'].includes(String(q.priority).toLowerCase())
          ? String(q.priority).toLowerCase()
          : 'medium',
        question: q.question || 'Point to clarify',
        askTo: ['lawyer', 'counterparty', 'both'].includes(String(q.askTo).toLowerCase())
          ? String(q.askTo).toLowerCase()
          : 'both',
        contextAndTalkingPoint: q.contextAndTalkingPoint || '',
      };
    });
  } else {
    normalized.questionsToAsk = [];
  }

  // 10. whatsappSummary (might be whatsAppSummary or whatsapp_summary)
  if (!normalized.whatsappSummary && normalized.whatsAppSummary) {
    normalized.whatsappSummary = normalized.whatsAppSummary;
  }
  if (!normalized.whatsappSummary && normalized.whatsapp_summary) {
    normalized.whatsappSummary = normalized.whatsapp_summary;
  }
  if (typeof normalized.whatsappSummary !== 'string') {
    normalized.whatsappSummary = '';
  }

  // 11. rentalMathExtracted (might be rentalMath or rental_math)
  if (!normalized.rentalMathExtracted && normalized.rentalMath) {
    normalized.rentalMathExtracted = normalized.rentalMath;
  }
  if (!normalized.rentalMathExtracted && normalized.rental_math) {
    normalized.rentalMathExtracted = normalized.rental_math;
  }

  return normalized;
}

export async function analyzeDocumentService(rawParams: AnalyzeApiRequest): Promise<AnalyzeResult> {
  const params = AnalyzeApiRequestSchema.parse(rawParams);
  const cacheKey = computeCacheKey(params);
  const now = Date.now();
  const cached = cache.get(cacheKey);

  if (cached && now - cached.timestamp < CACHE_TTL_MS) {
    return cached.result;
  }

  const model = getGeminiModel();
  const prompt = buildAnalyzePrompt({
    documentText: params.documentText,
    documentType: params.documentType,
    jurisdictionState: params.jurisdictionState,
    language: params.language,
    isScanned: params.isScanned,
  });

  const response = await generateContentWithRetry({
    model,
    contents: prompt,
    config: {
      systemInstruction: SYSTEM_BASE,
      temperature: 0.2,
      responseMimeType: 'application/json',
    },
  });

  const rawResponseText = response.text || '';
  let validatedData: AnalyzeResult | null = null;
  let jsonParseError = '';

  try {
    const cleanJson = rawResponseText
      .trim()
      .replace(/^```json\s*/i, '')
      .replace(/\s*```$/i, '');
    const parsedJson = JSON.parse(cleanJson);
    const normalized = normalizeModelOutput(parsedJson);
    const zodValidation = AnalyzeResultSchema.safeParse(normalized);

    if (zodValidation.success) {
      validatedData = zodValidation.data;
    } else {
      jsonParseError = zodValidation.error.issues
        .map((i) => `${i.path.join('.')}: ${i.message}`)
        .join('; ');
      console.warn('Zod validation warning after normalization:', jsonParseError);
    }
  } catch (e: unknown) {
    jsonParseError = e instanceof Error ? e.message : 'Invalid JSON syntax';
    console.warn(
      'Initial JSON parsing error:',
      jsonParseError,
      'Raw response length:',
      rawResponseText.length
    );
  }

  // Single repair retry if initial format failed
  if (!validatedData) {
    try {
      const repairPrompt = buildRepairPrompt(rawResponseText, jsonParseError);
      const repairResponse = await generateContentWithRetry({
        model,
        contents: repairPrompt,
        config: {
          systemInstruction: SYSTEM_BASE,
          temperature: 0.1,
          responseMimeType: 'application/json',
        },
      });

      const repairedClean = (repairResponse.text || '')
        .trim()
        .replace(/^```json\s*/i, '')
        .replace(/\s*```$/i, '');
      const repairedParsed = JSON.parse(repairedClean);
      const normalizedRepaired = normalizeModelOutput(repairedParsed);
      const secondValidation = AnalyzeResultSchema.safeParse(normalizedRepaired);

      if (secondValidation.success) {
        validatedData = secondValidation.data;
      }
    } catch (retryError) {
      console.warn('Repair retry failed for document analysis:', retryError);
    }
  }

  if (!validatedData) {
    throw new Error('Could not parse valid structured analysis from AI output.');
  }

  // Hallucination Guard: Verify verbatim quotes against original document text
  const { verifiedItems: verifiedClauses, report } = verifyQuotes<ClauseCard>(
    validatedData.clauses,
    params.documentText
  );

  const keyDates = validatedData.keyDatesAndDeadlines || validatedData.keyDates || [];
  const actionChecklist = validatedData.actionChecklist || [];

  const highRisks = verifiedClauses.filter((c: ClauseCard) => c.risk === 'high');
  const lawyerBrief = validatedData.lawyerBrief || {
    executiveSummary: `${params.documentType} governed by ${params.jurisdictionState} jurisdiction. Flagged ${highRisks.length} elevated risks.`,
    prioritizedQuestions: validatedData.questionsToAsk?.map((q) => q.question) || [],
    negotiationPoints: highRisks.map((c: ClauseCard) => c.title).slice(0, 5),
  };

  const finalResult: AnalyzeResult = {
    ...validatedData,
    clauses: verifiedClauses,
    keyDates,
    keyDatesAndDeadlines: keyDates,
    actionChecklist,
    lawyerBrief,
    verificationReport: report,
  };

  // Cache management
  if (cache.size >= MAX_CACHE_SIZE) {
    const firstKey = cache.keys().next().value;
    if (firstKey) cache.delete(firstKey);
  }
  cache.set(cacheKey, { timestamp: now, result: finalResult });

  return finalResult;
}
