'use client';

import React, { useState } from 'react';
import { Info, X, ShieldCheck, AlertCircle } from 'lucide-react';

export function DisclaimerBanner() {
  const [isDismissedOnMobile, setIsDismissedOnMobile] = useState(false);
  const [showFullDetailsModal, setShowFullDetailsModal] = useState(false);

  return (
    <>
      {/* Banner */}
      <aside
        id="clausewise-disclaimer-banner"
        aria-label="Legal information disclaimer"
        className={`bg-surface-muted border-b border-border px-3 sm:px-4 py-2 text-xs text-text-muted transition-all ${
          isDismissedOnMobile ? 'hidden sm:block' : 'block'
        }`}
      >
        <div className="max-w-7xl mx-auto flex items-center justify-between gap-3">
          <div className="flex items-center gap-2 min-w-0">
            <AlertCircle className="w-3.5 h-3.5 text-primary shrink-0" aria-hidden="true" />
            <p className="font-medium truncate sm:whitespace-normal">
              <strong>Legal information, not legal advice.</strong> Designed to help you ask the
              right questions before signing.
            </p>
          </div>

          <div className="flex items-center gap-3 shrink-0">
            <div className="hidden md:flex items-center gap-1.5 text-text-muted">
              <ShieldCheck className="w-3.5 h-3.5 text-primary shrink-0" />
              <span>Processed in memory • Not stored</span>
            </div>

            <button
              type="button"
              onClick={() => setShowFullDetailsModal(true)}
              className="text-primary hover:underline font-semibold text-[11px] shrink-0 cursor-pointer"
            >
              Learn more
            </button>

            {/* Mobile collapse button */}
            <button
              type="button"
              onClick={() => setIsDismissedOnMobile(true)}
              className="sm:hidden w-6 h-6 rounded-full flex items-center justify-center text-text-muted hover:text-text cursor-pointer"
              aria-label="Dismiss disclaimer banner"
            >
              <X className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      </aside>

      {/* Floating Info Icon when collapsed on mobile */}
      {isDismissedOnMobile && (
        <button
          type="button"
          onClick={() => setIsDismissedOnMobile(false)}
          className="sm:hidden fixed top-14 right-2 z-20 bg-surface/90 backdrop-blur-xs border border-border text-text-muted p-1.5 rounded-full shadow-xs cursor-pointer"
          title="Show legal disclaimer"
          aria-label="Show legal disclaimer"
        >
          <Info className="w-4 h-4 text-primary" />
        </button>
      )}

      {/* Full Disclaimer Modal */}
      {showFullDetailsModal && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs animate-in fade-in-50 duration-150"
          role="dialog"
          aria-modal="true"
          aria-labelledby="disclaimer-modal-title"
        >
          <div className="bg-surface rounded-2xl border border-border max-w-md w-full p-6 shadow-2xl space-y-4">
            <div className="flex items-start justify-between gap-2">
              <div className="flex items-center gap-2">
                <AlertCircle className="w-5 h-5 text-primary" />
                <h3 id="disclaimer-modal-title" className="text-base font-bold text-text">
                  Legal Disclaimer & Privacy
                </h3>
              </div>
              <button
                type="button"
                onClick={() => setShowFullDetailsModal(false)}
                className="w-8 h-8 rounded-full bg-surface-muted flex items-center justify-center text-text-muted hover:text-text cursor-pointer"
                aria-label="Close modal"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <div className="space-y-3 text-xs sm:text-sm text-text-muted leading-relaxed">
              <p>
                <strong>ClauseWise provides legal information, not legal advice.</strong>
              </p>
              <p>
                The analysis, risk indicators, and questions generated by ClauseWise are intended to
                help non-lawyers navigate contracts with greater confidence. They do not constitute
                attorney-client privilege or professional legal counsel.
              </p>
              <div className="p-3 rounded-xl bg-surface-muted border border-border flex items-start gap-2">
                <ShieldCheck className="w-4 h-4 text-primary shrink-0 mt-0.5" />
                <p className="text-xs text-text">
                  <strong>Privacy First:</strong> Your document text is processed purely in volatile
                  memory to perform the analysis. It is never saved to a database, sold, or
                  retained.
                </p>
              </div>
            </div>

            <button
              type="button"
              onClick={() => setShowFullDetailsModal(false)}
              className="w-full py-2.5 rounded-xl bg-primary text-primary-foreground font-semibold text-xs hover:opacity-95 transition cursor-pointer min-h-[44px]"
            >
              I Understand
            </button>
          </div>
        </div>
      )}
    </>
  );
}
